# Generated by Django 3.2 on 2023-06-13 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Categoría', max_length=100, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Marca', max_length=100, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Unidad Medida', max_length=100, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la Categoría', max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.categoria')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sub Categorias',
                'unique_together': {('categoria', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('codigo_barra', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.FloatField(default=0)),
                ('existencia', models.IntegerField(default=0)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('zona', models.CharField(choices=[('Seleccione..', 'Seleccione..'), ('Zona 1', 'Zona 1'), ('Zona 2', 'Zona 2'), ('Zona 3', 'Zona 3'), ('Zona 4', 'Zona 4'), ('Zona 5', 'Zona 5'), ('Zona 6', 'Zona 6'), ('Todas', 'Zona 7'), ('Todas', 'Todas')], default='Moneda..', max_length=20)),
                ('espesor', models.CharField(blank=True, max_length=50, null=True)),
                ('densidad', models.CharField(blank=True, max_length=50, null=True)),
                ('coeficiente_conductividad', models.CharField(blank=True, max_length=50, null=True)),
                ('vigencia_inscripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('usos', models.TextField(blank=True, max_length=200, null=True)),
                ('glosa', models.TextField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[(0, 'Seleccione..'), (1, 'CLP'), (2, 'USD'), (3, 'YEN'), (4, 'EU'), (5, 'OTR')], default='Moneda..', max_length=20)),
                ('consumo', models.CharField(blank=True, max_length=50, null=True)),
                ('clase_energetica', models.CharField(choices=[('Etiquetado..', 'Etiquetado..'), ('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('G', 'D'), ('G', 'E'), ('G', 'F'), ('G', 'G'), ('Energy Start', 'Energy start'), ('No Informa', 'No Informa')], default='Moneda..', max_length=20)),
                ('potencia', models.CharField(blank=True, max_length=50, null=True)),
                ('eficiencia_energetica', models.CharField(blank=True, max_length=50, null=True)),
                ('url_ult_precio', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_constructora', models.FloatField(default=0)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('resistencia_termica', models.CharField(blank=True, max_length=50, null=True)),
                ('transmitacia_termica', models.CharField(blank=True, max_length=50, null=True)),
                ('huella_carbono', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.marca')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.subcategoria')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.unidadmedida')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
