# Generated by Django 3.2 on 2023-06-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='huella_carbono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
