# Generated by Django 3.2 on 2023-06-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_alter_producto_huella_carbono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='huella_carbono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
