# Generated by Django 3.2 on 2023-06-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_auto_20230613_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='clase_energetica',
            field=models.CharField(choices=[('Etiquetado..', 'Etiquetado..'), ('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('Energy Start', 'Energy start'), ('No Informa', 'No Informa')], default='Seleccione..', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('Moneda..', 'Seleccione..'), ('CLP', 'CLP'), ('USD', 'USD'), ('YEN', 'YEN'), ('EU', 'EU'), ('OTR', 'OTR')], default='Seleccione..', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='zona',
            field=models.CharField(choices=[('Seleccione..', 'Seleccione..'), ('Zona 1', 'Zona 1'), ('Zona 2', 'Zona 2'), ('Zona 3', 'Zona 3'), ('Zona 4', 'Zona 4'), ('Zona 5', 'Zona 5'), ('Zona 6', 'Zona 6'), ('Todas', 'Zona 7'), ('Todas', 'Todas')], default='Seleccione..', max_length=20),
        ),
    ]
