# Generated by Django 3.2 on 2023-06-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20230613_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='coeficiente_conductividad2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='coeficiente_conductividad3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='coeficiente_conductividad4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='coeficiente_conductividad5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='coeficiente_conductividad6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='coeficiente_conductividad7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='densidad2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='densidad3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='densidad4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='densidad5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='densidad6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='densidad7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='espesor2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='espesor3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='espesor4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='espesor5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='espesor6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='espesor7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='resistencia_termica2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='resistencia_termica3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='resistencia_termica4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='resistencia_termica5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='resistencia_termica6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='resistencia_termica7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='transmitacia_termica2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='transmitacia_termica3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='transmitacia_termica4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='transmitacia_termica5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='transmitacia_termica6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='transmitacia_termica7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='vigencia_inscripcion2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='vigencia_inscripcion3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='vigencia_inscripcion4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='vigencia_inscripcion5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='vigencia_inscripcion6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='vigencia_inscripcion7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='zona2',
            field=models.CharField(choices=[('Seleccione..', 'Seleccione..'), ('Zona 1', 'Zona 1'), ('Zona 2', 'Zona 2'), ('Zona 3', 'Zona 3'), ('Zona 4', 'Zona 4'), ('Zona 5', 'Zona 5'), ('Zona 6', 'Zona 6'), ('Todas', 'Zona 7'), ('Todas', 'Todas')], default='Seleccione..', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='zona3',
            field=models.CharField(choices=[('Seleccione..', 'Seleccione..'), ('Zona 1', 'Zona 1'), ('Zona 2', 'Zona 2'), ('Zona 3', 'Zona 3'), ('Zona 4', 'Zona 4'), ('Zona 5', 'Zona 5'), ('Zona 6', 'Zona 6'), ('Todas', 'Zona 7'), ('Todas', 'Todas')], default='Seleccione..', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='zona4',
            field=models.CharField(choices=[('Seleccione..', 'Seleccione..'), ('Zona 1', 'Zona 1'), ('Zona 2', 'Zona 2'), ('Zona 3', 'Zona 3'), ('Zona 4', 'Zona 4'), ('Zona 5', 'Zona 5'), ('Zona 6', 'Zona 6'), ('Todas', 'Zona 7'), ('Todas', 'Todas')], default='Seleccione..', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='zona5',
            field=models.CharField(choices=[('Seleccione..', 'Seleccione..'), ('Zona 1', 'Zona 1'), ('Zona 2', 'Zona 2'), ('Zona 3', 'Zona 3'), ('Zona 4', 'Zona 4'), ('Zona 5', 'Zona 5'), ('Zona 6', 'Zona 6'), ('Todas', 'Zona 7'), ('Todas', 'Todas')], default='Seleccione..', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='zona6',
            field=models.CharField(choices=[('Seleccione..', 'Seleccione..'), ('Zona 1', 'Zona 1'), ('Zona 2', 'Zona 2'), ('Zona 3', 'Zona 3'), ('Zona 4', 'Zona 4'), ('Zona 5', 'Zona 5'), ('Zona 6', 'Zona 6'), ('Todas', 'Zona 7'), ('Todas', 'Todas')], default='Seleccione..', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='zona7',
            field=models.CharField(choices=[('Seleccione..', 'Seleccione..'), ('Zona 1', 'Zona 1'), ('Zona 2', 'Zona 2'), ('Zona 3', 'Zona 3'), ('Zona 4', 'Zona 4'), ('Zona 5', 'Zona 5'), ('Zona 6', 'Zona 6'), ('Todas', 'Zona 7'), ('Todas', 'Todas')], default='Seleccione..', max_length=20),
        ),
    ]
